name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Setup project
        run: yarn install --frozen-lockfile

      - name: Test project
        run: yarn run check

      - name: Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}